
export const codeComment = `// Code generated by Prisma (prisma@1.3.4). DO NOT EDIT.
  // Please don't change this file manually but run \`prisma generate\` to update it.
  // For more information, please read the docs: https://www.prisma.io/docs/prisma-client/`;
